"""Contract and test skeleton generator for AgentFlow tasks."""

import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class GeneratedArtifacts:
    stubs: list[Path] = field(default_factory=list)
    skeletons: list[Path] = field(default_factory=list)
    mocks: list[Path] = field(default_factory=list)


_FUNC_PATTERN = re.compile(
    r'\b(?:expose|implement|add|create|provide)\s+`?([a-zA-Z_][a-zA-Z0-9_]*)\s*\(([^)]*)\)`?',
    re.IGNORECASE,
)
_PUNC_RE = re.compile(r'[^a-z0-9]+')


def _scenario_to_method(scenario: str) -> str:
    name = _PUNC_RE.sub('_', scenario.lower()).strip('_')
    return ('test_' + name)[:64]


def _infer_functions(description: str) -> list[tuple[str, str]]:
    """Return list of (name, args) tuples parsed from description."""
    return [(m.group(1), m.group(2).strip()) for m in _FUNC_PATTERN.finditer(description)]


def _module_name(py_path: str) -> str:
    return Path(py_path).stem.replace('-', '_')


def generate_stub(owned_file: str, project_root: Path, task: dict | None = None) -> Path:
    """Generate a stub file at owned_file relative to project_root. Idempotent."""
    out = project_root / owned_file
    if out.exists():
        return out
    out.parent.mkdir(parents=True, exist_ok=True)

    if not owned_file.endswith('.py'):
        out.touch()
        return out

    task_id = (task or {}).get('task_id', '')
    title = (task or {}).get('title', '')
    description = (task or {}).get('description', '')
    functions = _infer_functions(description)

    lines = [f'"""Stub for {task_id}: {title}."""']
    lines.append('# Generated by AgentFlow contract generator.')
    lines.append('# Implement the functions below to make the tests pass.')

    if functions:
        for name, args in functions:
            lines.append('')
            lines.append('')
            arg_str = args if args else ''
            lines.append(f'def {name}({arg_str}):')
            lines.append('    raise NotImplementedError')
    else:
        lines.append('')
        lines.append('# No functions inferred — implement the module per your task brief.')
        lines.append('raise NotImplementedError')

    out.write_text('\n'.join(lines) + '\n')
    return out


def generate_test_skeleton(task: dict, project_root: Path) -> Path | None:
    """Generate a test skeleton for the task's unit scenarios. Idempotent."""
    test_reqs = task.get('test_requirements', {})
    unit_scenarios = test_reqs.get('unit', [])
    if not unit_scenarios:
        return None

    # derive skeleton path from first owned .py file
    owned_py = next(
        (f for f in task.get('owns', []) if f.endswith('.py') and not f.startswith('tests/')),
        None,
    )
    if owned_py is None:
        return None

    mod_name = _module_name(owned_py)
    pkg_parts = Path(owned_py).parts[1:-1]  # strip agentflow/ prefix and filename
    rel_dir = Path('tests').joinpath(*pkg_parts)
    skeleton_path = project_root / rel_dir / f'test_{mod_name}.py'

    if skeleton_path.exists():
        return skeleton_path

    skeleton_path.parent.mkdir(parents=True, exist_ok=True)

    class_name = 'Test' + ''.join(p.capitalize() for p in mod_name.split('_'))
    task_id = task.get('task_id', '')
    title = task.get('title', '')

    lines = [
        f'"""Test skeleton for {task_id}: {title}."""',
        'import pytest',
        '',
        '',
        f'class {class_name}:',
    ]
    for scenario in unit_scenarios:
        method = _scenario_to_method(scenario)
        lines.append('')
        lines.append(f'    def {method}(self):')
        lines.append(f'        raise NotImplementedError  # scenario: {scenario}')

    skeleton_path.write_text('\n'.join(lines) + '\n')
    return skeleton_path


def generate_mock_fixtures(task: dict, project_root: Path) -> Path | None:
    """Generate conftest.py with empty fixtures for IO boundaries. Idempotent."""
    reads = task.get('reads', [])
    io_boundaries = [
        r for r in reads
        if 'tools/' in r or not r.startswith('agentflow/')
    ]
    if not io_boundaries:
        return None

    # place conftest alongside the test skeleton
    owned_py = next(
        (f for f in task.get('owns', []) if f.endswith('.py') and not f.startswith('tests/')),
        None,
    )
    if owned_py is None:
        return None

    pkg_parts = Path(owned_py).parts[1:-1]
    conftest_path = project_root / Path('tests').joinpath(*pkg_parts) / 'conftest.py'

    if conftest_path.exists():
        return conftest_path

    conftest_path.parent.mkdir(parents=True, exist_ok=True)

    lines = ['"""Auto-generated IO mock fixtures."""', 'import pytest', '']
    for boundary in io_boundaries:
        fixture_name = 'mock_' + _PUNC_RE.sub('_', Path(boundary).stem.lower()).strip('_')
        lines += ['', f'@pytest.fixture', f'def {fixture_name}():', '    pass  # TODO: implement mock']

    conftest_path.write_text('\n'.join(lines) + '\n')
    return conftest_path


def generate_contracts(task: dict, project_root: Path) -> GeneratedArtifacts:
    """Generate stub + skeleton + mock files for a task. Idempotent."""
    artifacts = GeneratedArtifacts()

    for owned_file in task.get('owns', []):
        if owned_file.startswith('tests/'):
            continue
        path = generate_stub(owned_file, project_root, task)
        artifacts.stubs.append(path)

    skeleton = generate_test_skeleton(task, project_root)
    if skeleton:
        artifacts.skeletons.append(skeleton)

    mock = generate_mock_fixtures(task, project_root)
    if mock:
        artifacts.mocks.append(mock)

    return artifacts
